### ISSUE TITLE
Little glitch in uci options implementation

### ISSUE THREAD

**Issue by rwbc** [philipplenk/paulchen332#1]
Hi Philipp,

Thanks for the release of your uci chess program!

I found a little glitch with the uci options implementation. after I noticed hash was not changed in the CuteChess GUI.
Testing from cmd confirmed that it does not know 'name' which is required for setting an uci option.

```
* setoption name <id> [value <x>]
    this is sent to the engine when the user wants to change the internal parameters
    of the engine. For the "button" type no value is needed.
    One string will be sent for each parameter and this will only be sent when the engine is waiting.
    The name and value of the option in <id> should not be case sensitive and can inlude spaces.
    The substrings "value" and "name" should be avoided in <id> and <x> to allow unambiguous parsing,
    for example do not use <name> = "draw value".
    Here are some strings for the example below:
       "setoption name Nullmove value true\n"
      "setoption name Selectivity value 3\n"
       "setoption name Style value Risky\n"
       "setoption name Clear Hash\n"
       "setoption name NalimovPath value c:\chess\tb\4;c:\chess\tb\5\n"
```

```
uci
id name paulchen332 v0.1
id author Philipp Lenk
option name Hash type spin default 32 min 0 max 4096
uciok
ucinewgame
isready
readyok
position startpos
setoption name Hash value 256
info string trying to set option 'name Hash' to '256'
info string unknown option 'name Hash'
setoption Hash value 256
info string trying to set option 'Hash' to '256'
go infinite
info depth 1 seldepth 1  score cp 63 time 0 pv e2e4 nodes 21
...
info depth 18 seldepth 26  score cp 19 time 27640 pv e2e4 c7c5 b1c3 b8c6 f1c4 g8f6 nodes 1985409
```
**Edit:**
And this is also a confirmation that the win no popcount version works :)
(also compiling shows no problem for windows and gives around the same speed than yours)

Guenther (RWBC)
https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM

**Comment by philipplenk** [comment]
Hi Guenther,

thank you very much for testing and reporting the issue. Glad to know the Windows version works as well, I am most grateful.

Apparently, I should pay more attention when reading the specification. Should be fixed with 1c24383060e3f1536ee18a9176a7a5ffaf722f1d

Thanks again!
